apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote-api
  name: vote-api
  namespace: vote-example
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  selector:
    app: vote-api
