apiVersion: v1
kind: Service
metadata:
  labels:
    app: pipelines-vote-api
  name: pipelines-vote-api
  #namespace: vote-example
  namespace: pipelines-tutorial
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  selector:
    app: pipelines-vote-api
